Feat/planning events
PlanGo-app/PlanGo_api pull request #9
Opened 2021-11-25 20:00 UTC by DwightMint

2021-11-27 17:25 UTC, annelcarlier requested changes

2021-11-27 17:25 UTC, annelcarlier commented on src/main/java/com/plango/api/dto/planningevent/UpdatePlanningEventDto.java
> +    private String name;
L'attribut "name" sera-t-il vraiment modifié/voir même utilisé ? -> plutôt récupérer le nom du lieu du Pin pour l'affichage

2021-11-27 17:25 UTC, annelcarlier commented on src/main/java/com/plango/api/service/PlanningEventService.java
> +        travelService.getTravelById(createPlanningEventDto.getTravel().getId());
Pourquoi pas vérifier les autres entités ? (Pin pin / PlanningEvent eventAfter)

2021-11-27 17:25 UTC, annelcarlier commented on src/main/java/com/plango/api/controller/PlanningEventController.java
> +public interface PlanningEventController {
Manque route POST createPlanningEvent et DELETE deletePlanningEvent

2021-11-27 17:25 UTC, annelcarlier commented on src/main/java/com/plango/api/service/PlanningEventService.java
> +            if(!planningEvent.getCreatedBy().equals(user)) {
Peut-être autoriser les admins à modifier tous les éléments du planning ?

2021-11-27 17:25 UTC, annelcarlier commented on src/main/java/com/plango/api/service/PlanningEventService.java
> +            throw new CurrentUserAuthorizationException("Issue will trying to authenticate current user");
"Issue WHILE ..."

2021-11-27 17:25 UTC, annelcarlier commented on src/main/java/com/plango/api/service/TravelService.java
> +    // (un organizer peut également se rétrograder)
OK

2021-11-27 17:27 UTC, DwightMint commented on src/main/java/com/plango/api/controller/PlanningEventController.java
> +public interface PlanningEventController {
C'est volontaire, la création/suppression se fait via la création suppression d'un pin

2021-11-27 17:28 UTC, DwightMint commented on src/main/java/com/plango/api/dto/planningevent/UpdatePlanningEventDto.java
> +    private String name;
Oui je pensais mettre le nom du lieu pendant la création du pin qui créé en même temps l'event lié

2021-11-28 11:12 UTC, DwightMint commented on src/main/java/com/plango/api/service/PlanningEventService.java
> +        travelService.getTravelById(createPlanningEventDto.getTravel().getId());
Ajout du contrôle du pin fait, mais pas besoin de contrôle sur l'eventAfter car il peut être null

2021-11-28 11:35 UTC, merged